item {
  id: 1
  name: 'Private'
}

item {
  id: 2
  name: 'Truck'
}

item {
  id: 3
  name: 'Bus'
}

item {
  id: 4
  name: 'SharedTaxi'
}

item {
  id: 5
  name: 'Transit'
}

item {
  id: 6
  name: 'SUV'
}

item {
  id: 7
  name: 'Commercial'
}